### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by forrestsun** [WalterShe/dailyReport#1]
测试系统
ubuntu 13.04 64
redis Redis server v=2.6.7 sha=00000000:0 malloc=jemalloc-3.0.0 bits=64
node v0.10.13

1、linux下安装完成后报
module.js:340
    throw err;
          ^
Error: Cannot find module './vo/response'
解决办法：将vo目录下大写的Response.js改为小写response.js

2、根据说明将
hmset users 1:user_name adminn 1:password 20eabe5d64b0e216796e834f52d61f写入redis数据库，也执行了 redis 127.0.0.1:6379> sadd administrators 1 显示正常
测试数据：
redis 127.0.0.1:6379> hmget users 1:user_name 1:password
1) "adminn"
2) "20eabe5d64b0e216796e834f52d61f"

但网站启动后报“密码错误”，请问是何原因，谢谢！

**Comment by forrestsun** [comment]
问题解决：在ubuntu 下运行下面的代码自行生成‘1234567’的加密码为：20eabe5d64b0e216796e834f52d61fd0b70332fc，不知是何原因

或者在本地新建立一个app.js 运行如下代码，自行生成密钥
//app.js
var crypto = require('crypto');
hashedPassword=crypto.createHash("sha1").update('1234567').digest('hex')
console.log(hashedPassword);

**Comment by WalterShe** [comment]
Response.js 大小写在ubuntu下报错我再查下原因，我是在Mac系统下编写的，没有该问题。

密码问题我再想一个更好的方案。

**Comment by WalterShe** [comment]
Response.js 大小写在ubuntu下报错问题已经修复。版本号为：0ca2e60752 。提交时间为：2013-7-23

**Comment by WalterShe** [comment]
Response.js 大小写在ubuntu下报错问题已经修复。下载最新版即可

**Comment by WalterShe** [comment]
第一次部署成功后通过/install可以创建一个默认管理员账户，不需要手动的方式添加管理员账户到redis数据库了。

**Comment by forrestsun** [comment]
问题解决，上来关闭（刚知道要自觉关闭），呵呵
