### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by forrestsun** [WalterShe/dailyReport#2]
反复点击后报错：
GET /admin/users 304 3ms
GET /css/bootstrap.min.css 304 5ms
GET /css/pepper-grinder/jquery-ui-1.10.3.custom.min.css 304 4ms
GET /css/adminStyle.css 304 4ms
GET /js/jquery-1.9.1.min.js 304 3ms
GET /js/jquery-ui-1.10.3.custom.min.js 304 4ms
GET /js/bootstrap.min.js 304 3ms
GET /js/knockout-2.2.1.js 304 3ms
GET /js/TreeList.js 304 2ms
GET /js/admin/DepartmentUserMode.js 304 3ms
GET /js/admin/users.js 304 2ms
GET /admin/alldepartments 200 4ms
GET /admin/getallusers 200 4ms
GET /admin 304 2ms
GET /css/bootstrap.min.css 304 5ms
GET /css/adminStyle.css 304 4ms
GET /css/pepper-grinder/jquery-ui-1.10.3.custom.min.css 304 4ms
GET /js/jquery-1.9.1.min.js 304 5ms
GET /js/jquery-ui-1.10.3.custom.min.js 304 4ms
GET /js/bootstrap.min.js 304 3ms
GET /js/knockout-2.2.1.js 304 1ms
GET /js/TreeList.js 304 3ms
GET /js/admin/DepartmentUserMode.js 304 2ms
GET /js/admin/department.js 304 2ms
GET /admin/alldepartments 200 3ms
GET /logout 302 1ms
GET /login 304 2ms
GET /css/reportStyle.css 304 4ms
GET /css/bootstrap.min.css 304 5ms
GET /js/jquery-1.9.1.min.js 304 4ms
GET /js/bootstrap.min.js 304 4ms
GET /js/knockout-2.2.1.js 304 3ms
GET /js/admin/DepartmentUserMode.js 304 3ms
GET /js/login.js 304 1ms
POST /login 200 3ms
GET /show 200 6ms
GET /css/bootstrap.min.css 304 4ms
GET /css/reportStyle.css 304 4ms
GET /css/pepper-grinder/jquery-ui-1.10.3.custom.min.css 304 5ms
GET /js/jquery-1.9.1.min.js 304 4ms
GET /js/jquery-ui-1.10.3.custom.min.js 304 3ms
GET /js/bootstrap.min.js 304 4ms
GET /js/knockout-2.2.1.js 304 3ms
GET /js/ReportModel.js 304 3ms
GET /js/reportBase.js 304 2ms
GET /js/showreports.js 404 3ms
GET /write 200 12ms
GET /css/bootstrap.min.css 304 6ms
GET /css/reportStyle.css 304 7ms
GET /css/pepper-grinder/jquery-ui-1.10.3.custom.min.css 304 6ms
GET /js/jquery-1.9.1.min.js 304 6ms
GET /js/jquery-ui-1.10.3.custom.min.js 304 5ms
GET /js/bootstrap.min.js 304 4ms
GET /ueditor/editor_config.js 304 6ms
GET /ueditor/editor_all.js 304 5ms
GET /js/knockout-2.2.1.js 304 6ms
GET /js/validator.js 304 4ms
GET /js/ReportModel.js 304 3ms
GET /js/writereport.js 404 4ms
GET /showsubordinate 200 6ms
GET /css/bootstrap.min.css 304 5ms
GET /css/reportStyle.css 304 5ms
GET /css/pepper-grinder/jquery-ui-1.10.3.custom.min.css 304 5ms
GET /js/jquery-1.9.1.min.js 304 5ms
GET /js/jquery-ui-1.10.3.custom.min.js 304 5ms
GET /js/subordinateReports.js 200 8ms
GET /js/bootstrap.min.js 304 2ms
GET /js/knockout-2.2.1.js 304 3ms
GET /js/ReportModel.js 304 3ms
GET /js/TreeList.js 304 2ms
GET /js/reportBase.js 304 3ms

/home/sunsl/dailyreport/node_modules/redis/index.js:551
            throw err;
                  ^
RangeError: Maximum call stack size exceeded

**Comment by WalterShe** [comment]
我怀疑还是Response.js 大小写问题，使用github仓库最新代码后还有问题么，如果还有你把点击顺序告诉我。谢谢了。

**Comment by forrestsun** [comment]
更新后登录正常，问题解决

**Comment by forrestsun** [comment]
问题解决，上来关闭（刚知道要自觉关闭），呵呵
