### ISSUE TITLE
无法发布日志

### ISSUE THREAD

**Issue by forrestsun** [WalterShe/dailyReport#3]
测试系统
ubuntu 13.04 64
redis Redis server v=2.6.7 sha=00000000:0 malloc=jemalloc-3.0.0 bits=64
node v0.10.13

代码已更新。
运行后创建新的部门及相关人员
部门：研发中心 员工：forrest 密码：1111111
登录后点击编写日报，录入数据： 2012-1-1或 2012/1/1 内容：测试数据 或 test data
点击发布无反应用
控制台输出：
GET /js/writereport.js 404 4ms
GET /show 304 12ms
GET /css/bootstrap.min.css 304 7ms
GET /js/bootstrap.min.js 304 6ms
GET /js/jquery-ui-1.10.3.custom.min.js 304 7ms
GET /js/jquery-1.9.1.min.js 304 7ms
GET /css/pepper-grinder/jquery-ui-1.10.3.custom.min.css 304 6ms
GET /css/reportStyle.css 304 6ms
GET /js/knockout-2.2.1.js 304 1ms
GET /js/ReportModel.js 304 2ms
GET /js/reportBase.js 304 1ms
GET /js/showreports.js 404 2ms

**Comment by WalterShe** [comment]
文件大小写问题，导致系统认为一些文件不存在，所以程序不能正常运行。Mac系统下好像对文件大小写不敏感，晚上回家我把文件大小写好好清查一下。

**Comment by WalterShe** [comment]
已经修复

**Comment by forrestsun** [comment]
问题解决

**Comment by forrestsun** [comment]
close #3
