### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by forrestsun** [WalterShe/dailyReport#4]
点击日报填写（重复多次，日期为同一天）
同一用户这时会显示多个同样日期的多条记录，前台显示是否可合并处理：）
![selection_005](https://f.cloud.github.com/assets/3189959/853046/0576a770-f4ca-11e2-8cb8-b67c9e521b40.png)
参考：同时这三条显示的顺序是最后编写的显示在上面是否合理？（如果按一天的时间轴来处理的话，是否应该放在最下面）

**Comment by WalterShe** [comment]
日报是一个严肃的事情，不可以随意提交。每日做完事情后，好好整理今天的事情然后提交日报。如果确实出现什么原因需要修改日报，可以先删除然后再重新写一遍。另外每个日报上级是可以发表评论（目前该功能还没有实现）的，当然了自己也可以通过发表评论的方式来完善或者补充日报。

**Comment by forrestsun** [comment]
明白你设计思路了，谢谢。我们的想法不太一样。

**Comment by forrestsun** [comment]
close #4
